Twitter-clone-2/app/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views 

app_name = 'authentication'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('password-reset/', views.ResetPasswordView.as_view(), name='password-reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
                                                     success_url=reverse_lazy('authentication:password-reset-complete')),
         name='password-reset-confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password-reset-complete')
]

Twitter-clone-2/app/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from tweets.views import Feed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Feed.as_view(), name='feed'),
    path('authentication/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls')),
    path('tweets/', include('tweets.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Twitter-clone-2/app/profiles/urls.py
from django.urls import path

from . import views 

app_name = 'profiles'

urlpatterns = [
    path('my/', views.MyProfile.as_view(), name='my'),
    path('edit/', views.ChangeProfile.as_view(), name='edit'),
    path('followed/', views.FollowedSection.as_view(), name='followed'),
    path('search/', views.ProfileSearch.as_view(), name='search'),
    path('interact/<int:user_id>/', views.interact, name='interact'),
    path('<slug:slug>/', views.ProfileDetail.as_view(), name='single'),
]

Twitter-clone-2/app/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

# Create your models here.

class UserManager(BaseUserManager):
    
    def create_user(self, email, password=None, full_name=None, **extra_fields):
        if not email:
            raise ValueError("Users must have an email!")
        
        if not password:
            raise ValueError("Users must have a password!")
        
        user = self.model(
            email=self.normalize_email(email),
            full_name=full_name,
            **extra_fields 
        )
        user.set_password(password)
        user.save()
        return user 
    
    
    def create_superuser(self, email, password=None, full_name=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        
        return self.create_user(
            email=email,
            password=password,
            full_name=full_name,
            **extra_fields
        )
        
        
class User(AbstractBaseUser, PermissionsMixin):
    email = models.CharField(max_length=64, unique=True, db_index=True)
    full_name = models.CharField(max_length=64, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    
    USERNAME_FIELD = 'email'
    
    objects = UserManager()
    
    def __str__(self):
        return self.email 
    
    def get_full_name(self):
        return self.full_name if self.full_name else self.email 
    
    def get_short_name(self):
        if self.full_name:
            if ' ' in self.full_name:
                return self.full_name.split()[0]
            return self.full_name 
        return self.email 
    
    @property 
    def username(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_superuser 
    
    def has_module_perms(self, app_label):
        return self.is_superuser

Twitter-clone-2/app/accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from django.contrib.auth import get_user_model

import string

User = get_user_model()

class UserAdminCreationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_2 = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')

    class Meta:
        model = User
        fields = ['email','full_name']

    def clean(self):
        """
        Verify both password match
        """
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_2 = cleaned_data.get('password_2')
        if password is not None and password != password_2:
            self.add_error('password_2', 'Your passwords don\'t match.')

        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

class UserAdminChangeForm(forms.ModelForm):

    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ['email', 'full_name', 'is_active', 'is_staff', 'is_superuser']

    def clean_password(self):
        return self.initial['password']
    
    
class SignupForm(forms.ModelForm):
    
    password = forms.CharField(
        max_length=64, 
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': ''
        }))
    password_2 = forms.CharField(max_length=64, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': ''
    }), label="Repeat your password")
    
    class Meta:
        model = User 
        fields = ('email', 'full_name', 'password', 'password_2')
        widgets = {
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'abc123@gmail.com'
            }),
            'full_name': forms.TextInput(attrs={'class': 'form-control'})
        }
        
    def clean(self):
        data = super().clean()
        password = data.get('password')
        password_2 = data.get('password_2')
        if password and password != password_2:
            self.add_error('password_2', "Passwords don't match!")
        return data 
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user 
    
    
class LoginForm(forms.Form):
    
    email = forms.EmailField(max_length=64, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'somemail@gmail.com'
    }))
    password = forms.CharField(max_length=64, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
    }))

Twitter-clone-2/app/accounts/views.py
from django.shortcuts import render, redirect
from django.views import generic 
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.conf import settings
from django.urls import reverse_lazy
from django.utils.http import is_safe_url

from .models import User 
from .forms import SignupForm, LoginForm
# Create your views here.

class LoginView(generic.View):
    
    def get(self, *args, **kwargs):
        request = self.request 
        form = LoginForm()
        return render(request, 'accounts/login.html', {'form': form})
    
    def post(self, *args, **kwargs):
        request = self.request 
        form = LoginForm(request.POST)
        next_ = request.GET.get('next') or None 
        next_post = request.POST.get('next') or None
        redirect_path = next_ or next_post or None 
         
        if form.is_valid():
            user = authenticate(
                email=form.cleaned_data.get('email'),
                password=form.cleaned_data.get('password')
            )
            
            if user is not None:
                user_email = User.objects.get(
                    email=form.cleaned_data.get('email')    
                ).email
                login(request, user, backend="django.contrib.auth.backends.ModelBackend")
                messages.success(request, f"You have logged in as {user_email}.")
                # return redirect(settings.LOGIN_REDIRECT_URL)
                if is_safe_url(redirect_path, request.get_host()):
                    return redirect(redirect_path)
                return redirect('/')
            messages.warning(request, "You have provided invalid credentials.")
            return redirect('authentication:login')
        
        

class SignupView(generic.CreateView):
    
    model = User 
    form_class = SignupForm 
    success_url = reverse_lazy('hello')
    redirect_authenticated_user = True 
    template_name = 'accounts/signup.html'
    
    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
            messages.success(self.request, f"You have created an account!")
            return redirect(settings.LOGIN_REDIRECT_URL)         
        return super(SignupView, self).form_valid(form)
    
        
@login_required
def logout_view(request):
    logout(request)
    messages.success(request, "You have logged out.")
    return redirect(settings.LOGOUT_REDIRECT_URL)


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'accounts/password_reset.html'
    email_template_name = 'accounts/emails/password_reset_email.html'
    subject_template_name = 'accounts/emails/password_reset_subject.txt'
    success_message = """We've emailed you to give you a brief instruction on 
                        how to reset your password. If you've provided an invalid
                        email address, please try once again. Make sure to check
                        your spam folder."""
    success_url = reverse_lazy('profiles:my')
            

Twitter-clone-2/app/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load socialaccount %}
{% block title %}Login{% endblock title %}

{% block content %}
    <main class="my-3 auth-form-box">
        <div class="p-3 fs-2 bg-primary text-white rounded">
            <h1 class="display-5">Welcome to the login page!</h1>
        </div>
        <form action="/accounts/google/login/" class="m-2" id="google-oauth-form" method="POST">
            {% csrf_token %}
            <div class="d-grid gap-3">
            </div>
        </form>
        <button type="submit" form="google-oauth-form" class="btn btn-outline-light w-100 text-dark mb-2"><i class="fa fa-google"></i> Log in with Google</button>

        <form method="POST" class="p-3 shadow">
            {% csrf_token %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text pb-3" id="email-prefix"><i class="fa fa-envelope"></i></span>
                </div>
                {{form.email}}
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text pb-3" id="password-prefix"><i class="fa fa-eye-slash passwordVisibility" onclick="passwordTrigger();"></i></span>
                </div>
                {{form.password}}
            </div>
            
            <div class="d-flex justify-content-center gap-3">
                <button type="submit" class="btn btn-primary w-50">Log In</button> 
            </div>
        </form>

        <small class="text-muted">Don't have an account? <a href="{% url 'authentication:signup' %}">Sign up.</a></small><br>
        <small class="text-muted">Forgot your password? <a href="{% url 'authentication:password-reset' %}">Reset it here.</a></small>
    </main>
{% endblock content %}

Twitter-clone-2/app/accounts/templates/accounts/password_reset.html
{% extends "base.html" %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        <div class="alert alert-info alert-dismissible" role="alert">
                            <button class="btn btn-close" data-bs-dismiss="alert"></button>
                            <div>
                                <p>Please, note, that users signed up via Google won't receive any emails since Google account is their primary authentication tool.</p>
                            </div>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-2 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                {% if user.is_authenticated %}
                                    <a href="{% url 'profiles:my' %}">Back to profile</a>
                                {% else %}
                                    <a href="{% url 'authentication:signup' %}">Create A New Account</a><br><br>
                                    <a href="{% url 'authentication:login' %}">Back To Login</a><br>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>
{% endblock content %}

Twitter-clone-2/app/accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go back to your <a href="{% url 'profiles:my' %}">profile</a>.
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

Twitter-clone-2/app/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% block title %} Password Reset {% endblock title %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if validlink %}
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Reset Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Reset Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% else %}
                    <div class="alert alert-warning">
                        The password reset link was invalid, possibly because it has already been used.
                        Please request a new password reset.
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

Twitter-clone-2/app/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load socialaccount %}
{% block title %}Signup{% endblock title %}

{% block content %}
    <main class="my-3 auth-form-box">
        <div class="p-3 fs-2 bg-success text-white rounded">
            <h1 class="display-5">Welcome to the Signup page!</h1>
        </div>

        <form action="/accounts/google/login/" id="google-oauth-form" method="POST">
            {% csrf_token %}
        </form>

        <form method="POST" class="shadow p-3">
            {% csrf_token %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text pb-3" id="email-prefix"><i class="fa fa-envelope"></i></span>
                </div>
                {{form.email}}
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="fullname-prefix">Full Name</span>
                </div>
                {{form.full_name}}
            </div>
            <div class="row">
                <div class="col">
                    <label for="id_password" class="form-label">Enter password:</label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text pb-3 pw1-eye-box" id="pw1-prefix"><i class="fa fa-eye-slash passwordVisibility" onclick="passwordTrigger();"></i></span>
                        </div>
                        {{form.password}}
                    </div>
                </div>
                <div class="col">
                    <label for="id_password_2" class="form-label">Confirm password:</label>
                    {{form.password_2}}
                </div>
            </div>
            <div class="d-grid gap-3">
                <button type="submit" class="btn btn-success">Sign Up</button>
                <button type="submit" form="google-oauth-form" class="btn btn-success w-100"><i class="fa fa-google"></i> Sign Up with Google</button>
            </div>
        </form>

        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button class="btn btn-close" data-bs-dismiss="alert"></button>
            {% for key, value in form.errors.items %}
                <strong>{{ value }}</strong>
            {% endfor %}
        </div>
        {% endif %}

        <small class="text-muted">Already have an account? <a href="{% url 'authentication:login' %}">Log In.</a></small>
    </main>
{% endblock content %}