Twitter-clone-2/app/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views 

app_name = 'authentication'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('password-reset/', views.ResetPasswordView.as_view(), name='password-reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
                                                     success_url=reverse_lazy('authentication:password-reset-complete')),
         name='password-reset-confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password-reset-complete')
]

Twitter-clone-2/app/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from tweets.views import Feed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Feed.as_view(), name='feed'),
    path('authentication/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls')),
    path('tweets/', include('tweets.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Twitter-clone-2/app/profiles/urls.py
from django.urls import path

from . import views 

app_name = 'profiles'

urlpatterns = [
    path('my/', views.MyProfile.as_view(), name='my'),
    path('edit/', views.ChangeProfile.as_view(), name='edit'),
    path('followed/', views.FollowedSection.as_view(), name='followed'),
    path('search/', views.ProfileSearch.as_view(), name='search'),
    path('interact/<int:user_id>/', views.interact, name='interact'),
    path('<slug:slug>/', views.ProfileDetail.as_view(), name='single'),
]

Twitter-clone-2/app/templates/base/snippets/css.html
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" /> -->
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />

Twitter-clone-2/app/templates/base/snippets/footer.html
<footer class="mt-auto page-footer">
  <hr />
  <div class="mx-auto" align="center"></div>
  <div class="d-flex justify-content-around"></div>
</footer>

Twitter-clone-2/app/templates/base/snippets/js.html
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

Twitter-clone-2/app/templates/base/snippets/modal_form.html
{% load bootstrap5 %}
<div class="modal fade" id="{{modal_id}}" tabindex="-1" aria-labelledby="{{modal_label}}" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="{{modal_label}}" style="color: black;">{{label_text}}</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="charCountRefresh();"></button>
        </div>
        <div class="modal-body" style="color: black;">
          <form id="{{form_id}}" action="{{form_action}}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
          </form>
          <p class="fs-5 text-muted">
            <span class="actual">0</span>/<span class="max">140</span>
          </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="charCountRefresh();">Close</button>
          <button type="submit" form="{{form_id}}" class="btn btn-primary">Go!</button>
        </div>
      </div>
    </div>
  </div>

Twitter-clone-2/app/templates/base/snippets/navbar.html
{% url 'feed' as feed_url %}
{% url 'profiles:my' as my_profile_url %}
{% url 'profiles:followed' as followed_url %}
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        <i class="fa fa-twitter"></i> someTwi
      {% if user.is_authenticated %}
      | <span class="navbar-profile-link">
          {% if user.profile.profile_pic %}
            <img src="{{user.profile.profile_pic.url}}" class="profile-pic-thumbnail-xxs" alt="">
          {% endif %}
          {{user.profile.nickname}}
        </span>
      {% endif %}
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel"><i class="fa fa-cogs"></i> Site navigation</h5>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a href="/" class="nav-link {% if request.path == feed_url %}active{% endif %}"><i class="fa fa-globe"></i> Feed</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if request.path == my_profile_url %}active{% endif %}" aria-current="page" href="{% url 'profiles:my' %}"><i class="fa fa-home"></i> My Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == followed_url %}active{% endif %}" aria-current="page" href="{% url 'profiles:followed' %}"><i class="fa fa-users"></i> Followed Profiles</a>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-user-circle"></i> Authentication
              </a>
              <ul class="dropdown-menu dropdown-menu-dark">
                {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="{% url 'authentication:logout' %}"><i class="fa fa-sign-out"></i> Log out</a></li>
                <li><a class="dropdown-item" href="{% url 'authentication:password-reset' %}"><i class="fa fa-key"></i> Reset password</a></li>
                {% else %}
                <li><a class="dropdown-item" href="{% url 'authentication:login' %}"><i class="fa fa-sign-in"></i> Log In</a></li>
                <li><a class="dropdown-item" href="{% url 'authentication:signup' %}"><i class="fa fa-plus"></i> Create an account</a></li>
                {% endif %}
              </ul>
            </li>
          </ul>
          <hr>
          <h3 class="text-muted">Find users that interest you!</h3>
          <form class="d-flex mt-3 search-form" role="search" action="{% url 'profiles:search' %}">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search-q">
            <button class="btn btn-success search-btn" type="submit"><i class='fa fa-search'></i></button>
          </form>
        </div>
      </div>
    </div>
  </nav>