Twitter-clone-2/app/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from tweets.views import Feed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Feed.as_view(), name='feed'),
    path('authentication/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls')),
    path('tweets/', include('tweets.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Twitter-clone-2/app/profiles/urls.py
from django.urls import path

from . import views 

app_name = 'profiles'

urlpatterns = [
    path('my/', views.MyProfile.as_view(), name='my'),
    path('edit/', views.ChangeProfile.as_view(), name='edit'),
    path('followed/', views.FollowedSection.as_view(), name='followed'),
    path('search/', views.ProfileSearch.as_view(), name='search'),
    path('interact/<int:user_id>/', views.interact, name='interact'),
    path('<slug:slug>/', views.ProfileDetail.as_view(), name='single'),
]

Twitter-clone-2/app/tweets/urls.py
from django.urls import path

from . import views

app_name = 'tweets'

urlpatterns = [
    path('new/', views.AddTweet.as_view(), name='new'),
    path('reply/<int:tweet_id>/', views.add_reply, name='reply'),
    path('view/<int:tweet_id>/', views.tweet_detail, name='single'),
    path('view-branch/<int:tweet_id>/', views.tweet_branch_view, name='branch'),
    path('like/<int:tweet_id>/', views.like_unlike, name='like'),
    path('delete/<int:tweet_id>/', views.delete_tweet, name='delete'),
    path('retweet/<int:tweet_id>/', views.retweet, name='retweet')
]

Twitter-clone-2/app/tweets/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

from profiles.models import Profile

# Create your models here.
User = settings.AUTH_USER_MODEL


class TweetQueryset(models.query.QuerySet):

    def time_order(self):
        return self.order_by('-created')
    
    def reverse_time_order(self):
        return self.order_by('created')
    
    def no_replies(self):
        return self.filter(is_reply=False)


class TweetManager(models.Manager):

    def get_queryset(self):
        return TweetQueryset(self.model, using=self._db)

    def time_order(self):
        """This ordering is chronological and is
            meant for feed and profile sections"""
        return self.get_queryset().time_order()
    
    def reverse_time_order(self):
        """This ordering is meant for single tweet sections where replies 
            are meant to be displayed from the first down to the most recent one."""
        return self.get_queryset().reverse_time_order()
    
    def no_replies(self):
        return self.get_queryset().no_replies()


class Tweet(models.Model):

    author = models.ForeignKey(
        Profile, 
        on_delete=models.CASCADE, 
        related_name="tweets")
    text = models.CharField(max_length=140)
    image = models.ImageField(blank=True, null=True, upload_to='tweets/attachments/')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_reply = models.BooleanField(default=False)
    branch_start = models.ForeignKey(
        "self", 
        on_delete=models.CASCADE, 
        blank=True, 
        null=True, 
        related_name='branch_tweets')
    reply_to = models.ForeignKey(
        "self", 
        on_delete=models.CASCADE, 
        blank=True, 
        null=True, 
        related_name='replies')

    objects = TweetManager()
    
    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"author: {str(self.author)} tweet_id({self.id})"

    @property
    def like_count(self):
        return self.likes.all().count()

    @property 
    def retweet_count(self):
        return self.retweets.all().count()
    
    @property 
    def branch_length(self):
        return self.branch_tweets.all().count()
    
    @property 
    def reply_count(self):
        return self.replies.all().count()

    def get_absolute_url(self):
        return reverse("tweets:single", kwargs={'tweet_id': self.id})    
    
    def get_retweet_url(self):
        return reverse('tweets:retweet', kwargs={'tweet_id': self.id})
    

class LikedTweet(models.Model):
    profile = models.ForeignKey(
        Profile, 
        on_delete=models.CASCADE, 
        related_name="likes")
    tweet = models.ForeignKey(
        Tweet, 
        on_delete=models.CASCADE, 
        related_name="likes")
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"user=({self.profile.nickname}); tweet=({self.tweet.id})"
    
    
class Retweet(models.Model):
    profile = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name='retweets'
    )
    tweet = models.ForeignKey(
        Tweet,
        on_delete=models.CASCADE,
        related_name="retweets"
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"user=({self.profile.nickname}); tweet=({self.tweet.id})"
        

Twitter-clone-2/app/tweets/forms.py
from django import forms 

from .models import Tweet 


class TweetForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(TweetForm, self).__init__(*args, **kwargs)
        self.fields['text'] = forms.CharField(
            required=False,
            max_length=140,
            widget=forms.Textarea(attrs={
                'placeholder': "What's good?",
                'id': 'tweet-text-box',
                'maxlength': 140,
            })
        )
        
    class Meta:
        model = Tweet
        fields = ('text', 'image')

Twitter-clone-2/app/tweets/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.http import JsonResponse

from .forms import TweetForm
from .models import Tweet, LikedTweet, Retweet

from profiles.models import Profile
# Create your views here.


class Feed(generic.ListView):
    model = Tweet
    template_name = "feed.html"
    context_object_name = "tweets"
    
    def get_queryset(self):
        return self.model.objects.filter(is_reply=False).time_order()[:20]
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['hero_unit_msg'] = 'Stay tuned with the latest saying from the ' \
                                    'best and the smartest authors.'
        context['hero_unit_class'] = 'primary'
        return context


class AddTweet(LoginRequiredMixin, generic.CreateView):

    def post(self, *args, **kwargs):
        request = self.request
        form = TweetForm(request.POST, request.FILES or None)
        if form.is_valid():
            tweet_obj = form.save(commit=False)
            tweet_obj.author = request.user.profile
            if request.FILES.get('image', None) is not None:
                tweet_obj.image = request.FILES['image']
            tweet_obj.save()
            messages.success(request, "Net tweet added!")
            return redirect('profiles:my')

        messages.warning(request, "Something's wrong...")
        return redirect('profiles:my')


@login_required(redirect_field_name="next")
def like_unlike(request, tweet_id):
    tweet_obj = get_object_or_404(Tweet, id=tweet_id)
    profile_obj = request.user.profile
    liked_tweet, created = LikedTweet.objects.get_or_create(
        profile=profile_obj,
        tweet=tweet_obj
    )
    if not created:
        liked_tweet.delete()

    if request.is_ajax:
        json = {
            'liked': created,
            'unliked': not created,
            'like_count': tweet_obj.like_count
        }
        return JsonResponse(json)
    
    
@login_required 
def retweet(request, tweet_id):
    tweet_obj = get_object_or_404(Tweet, id=tweet_id)
    retweet_obj, created = Retweet.objects.get_or_create(
        profile=request.user.profile,
        tweet=tweet_obj
    )
    if not created:
        retweet_obj.delete()
    if request.is_ajax:
        data = {
            'created': created,
            'deleted': not created,
            'retweet_count': tweet_obj.retweet_count
        }
        return JsonResponse(data)


@login_required
def delete_tweet(request, tweet_id):
    tweet_obj = get_object_or_404(Tweet, id=tweet_id)
    profile_obj = request.user.profile
    try:
        related_like = LikedTweet.objects.get(
            profile=profile_obj,
            tweet=tweet_obj
        )
    except LikedTweet.DoesNotExist:
        related_like = None 
    if related_like:
        related_like.delete()
    tweet_obj.delete()
    messages.success(request, "Tweet has been successfully deleted!")
    return redirect(request.META.get('HTTP_REFERER'))


def tweet_detail(request, tweet_id):
    tweet_obj = get_object_or_404(Tweet, id=tweet_id)
    tweet_replies = tweet_obj.replies.all().reverse_time_order()
        
    context = {
        'tweet': tweet_obj,
        'tweet_replies': tweet_replies
    }
    return render(request, 'tweets/single.html', context)


def tweet_branch_view(request, tweet_id):
    tweet_obj = get_object_or_404(Tweet, id=tweet_id)
    branch_starter = tweet_obj.branch_start
    branch_tweets = branch_starter.branch_tweets.all().reverse_time_order()
    
    context = {
        'tweet': branch_starter,
        'tweet_replies': branch_tweets
    }
    return render(request, 'tweets/single.html', context)


@login_required 
def add_reply(request, tweet_id):
    tweet_obj = get_object_or_404(Tweet, id=tweet_id)
    reply_text = request.POST.get('replyText')
    reply_image = None
    if request.FILES.get('replyImage', None) is not None:
        reply_image = request.FILES['replyImage']
        
    reply_tweet = Tweet.objects.create(
        author=request.user.profile,
        text=reply_text,
        image=reply_image or None,
        is_reply=True,
        reply_to=tweet_obj
    )
    reply_tweet.branch_start = tweet_obj if not tweet_obj.is_reply \
                                else tweet_obj.branch_start
    reply_tweet.save()
    messages.success(request, "A reply has been added!")
    return redirect(request.META.get('HTTP_REFERER'))

Twitter-clone-2/app/tweets/templates/tweets/snippets/tweet.html
{% load static %}
<main class="my-3">
  <div class="row">
    <div class="col-6 d-flex flex-row gap-3">
      <img src="{% if tweet.author.profile_pic %}{{tweet.author.profile_pic.url}}{% else %}{% static 'images/no_photo_placeholder.png' %}{% endif %}" class="profile-img-thumbnail" style="height: 75px; width: 75px; border-radius: 50%;">

      <div class="d-flex flex-column">
        {% if tweet in retweets %}
          <span class="text-muted">
            <i class="fa fa-retweet"></i>{{profile.nickname}} retweeted from {{tweet.author.nickname}}
          </span>
        {% endif %}
        <h3 class="fs-4 mr-3">
          <a href="{% if tweet.author.user == request.user %}{% url 'profiles:my' %}{% else %}{{tweet.author.get_absolute_url}}{% endif %}">
            {{tweet.author.nickname}} 
          </a>{% if request.user == tweet.author.user %} <span class="text-muted fs-4">(You)</span>{% endif %}
          {% if tweet.is_reply %}replied to <a href="{% if tweet.reply_to.author.user == request.user %}{% url 'profiles:my' %}{% else %}{{tweet.repply_to.author.get_absolute_url}}{% endif %}">{{tweet.reply_to.author.nickname}}</a>{% endif %}
        </h3>
        {% if tweet.branch_start and not 'branch' in request.path %}
          <a href="{% url 'tweets:branch' tweet_id=tweet.id %}" class="branch-view-link"><i class='fa fa-share-square'></i> View full branch</a>
        {% endif %}
      </div>
    </div>
    <div class="col-6 d-flex flex-row-reverse gap-2">
      {% if tweet.author == current_profile %}
           
      <div class="dropdown">
        <button class="btn btn-link mb-5" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            <path d="M12 18c1.657 0 3 1.343 3 3s-1.343 3-3 3-3-1.343-3-3 1.343-3 3-3zm0-9c1.657 0 3 1.343 3 3s-1.343 3-3 3-3-1.343-3-3 1.343-3 3-3zm0-9c1.657 0 3 1.343 3 3s-1.343 3-3 3-3-1.343-3-3 1.343-3 3-3z"/>
          </svg>   
        </button>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#tweet{{tweet.id}}ConfirmDeleteModal"><i class="fa fa-trash" style="color:red"></i> Delete</a></li>
        </ul>
      </div>
      <!--
        TWEET CONFIRM DELETE MODAL
      -->
      <div class="modal fade" id="tweet{{tweet.id}}ConfirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-3" id="confirmDeleteModalLabel">Confirm Deletion?</h1>
            </div>
            <div class="modal-body">
              <p class="fs-4">
                Are you sure you want to delete this tweet?
              </p>
              <div class="m-3 border-top border-left border-right">
                <div class="d-flex justify-content-between gap-3">
                  <p class="fs-6">{{tweet.text}}</p>
                  <p class="fs-6 text-muted">{{tweet.created|timesince}} ago</p>
                </div>
                {% if tweet.image %}
                  <div align="center">
                    <img src="{{tweet.image.url}}" class="tweet-caption-img">
                  </div>
              {% endif %}
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Back to profile</button>
              <a href="{% url 'tweets:delete' tweet_id=tweet.id %}" class="btn btn-danger">Delete Tweet</a>
            </div>
          </div>
        </div>
      </div>
      <!--
        TWEET CONFIRM DELETE MODAL
      -->    
      {% endif %}
      <p class="fs-5 text-muted">{{tweet.created|timesince}} ago</p>
    </div>
  </div>
  <div class="tweet-content-box px-3">
    <p class="fs-5">
      {{tweet.text}}
    </p>
    {% if tweet.image %}
      <div align="center">
        <img src="{{tweet.image.url}}" class="tweet-caption-img">
      </div>
    {% endif %}
  </div>
  <div class="tweet-actions">
    <div class="d-flex flex-row">
      <a href="{{tweet.get_absolute_url}}" class="btn btn-link comment-button" onclick="this.blur();"><i class="fa fa-comment-o"></i>
        {% if not tweet.is_reply %}
          {{tweet.branch_length}}
        {% else %}
          {{tweet.reply_count}}
        {% endif %}
      </a>
      <button type="button" class="btn btn-link retweet-button" id="retweet-btn-{{tweet.id}}" onclick="this.blur();">
        <i class="fa fa-retweet"></i>
        <span id="{{tweet.id}}-retweet-count">{{tweet.retweet_count}}</span>
        <span id="{{tweet.id}}-retweet-check-box">
          {% if tweet in current_profile_retweets %}<i class="fa fa-check"></i>{% endif %}  
        </span>
      </button>
      <button type="button" class="btn btn-link like-button" id="like-btn-{{tweet.id}}" onclick="this.blur();">
        <span class="{{tweet.id}}-like-box">
          <i class="fa {% if tweet in current_profile_likes %}fa-heart{% else %}fa-heart-o{% endif %}"></i>
        </span>
        <span id="{{tweet.id}}-like-count">{{tweet.like_count}}</span>
      </button>


      <div class="dropdown">
        <a class="btn btn-link reply-btn" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fa fa-pencil"></i> Reply
        </a>
      
        <div class="dropdown-menu reply-dropdown w-50">
          <form class="px-4 py-3" method="POST" enctype="multipart/form-data" action="{% url 'tweets:reply' tweet_id=tweet.id %}">
            {% csrf_token %}
            <div class="mb-3">
              <label for="replyText" class="form-label">What would you say??</label>
              <textarea id="replyText" name="replyText" class="form-control" id="" cols="80" rows="5" maxlength="140"></textarea>
            </div>
            <p class="text-muted">
              <span class="reply-actual">0</span>/<span class="max">140</span>
            </p>
            <div class="mb-3">
              <label for="replyImage" class="form-label">Add caption</label>
              <input type="file" name="replyImage" accept="image/*" class="form-control" title>
            </div>
            <button type="submit" class="btn btn-primary">Reply</button>
          </form>
        </div>
      </div>


    </div>
  </div>
</main><hr>


<script type="text/javascript">
  var likeBtn = $("#like-btn-{{tweet.id}}")
  likeBtn.click(function(){
    var tweetId = "{{tweet.id}}";
    $.ajax({
      url: "{% url 'tweets:like' tweet_id=tweet.id %}",
      type: "POST",
      data: {
        "tweet_id": tweetId,
        "csrfmiddlewaretoken": "{{csrf_token}}"
      },
      dataType: 'json',
      success: function(json){
        var likeCounter = document.getElementById('{{tweet.id}}-like-count')
        likeCounter.innerHTML = json.like_count;
        var likeBox = $('.{{tweet.id}}-like-box')
        var heartIcon = likeBox.children('i')[0]
        if (json.liked){
          heartIcon.setAttribute('class', 'fa fa-heart')
        }else if (json.unliked) {
          heartIcon.setAttribute('class', 'fa fa-heart-o')
        }
      },
      error: function(err, xhr, msg) {}
    })
  })

  var retweetBtn = $('#retweet-btn-{{tweet.id}}');
  retweetBtn.click(function(){
    var tweetId = '{{tweet.id}}';
    $.ajax({
      url: '{{tweet.get_retweet_url}}',
      type: "POST",
      data: {
        'tweet_id': tweetId,
        'csrfmiddlewaretoken': '{{csrf_token}}'
      },
      dataType: 'json',
      success: function(json){
        var retweetCounter = $('#{{tweet.id}}-retweet-count');
        retweetCounter.text(json.retweet_count);
        var retweetCheckBox = document.getElementById('{{tweet.id}}-retweet-check-box');
        if (json.created){
          retweetCheckBox.innerHTML = '<i class="fa fa-check"></i>';
        } else if(json.deleted){
          retweetCheckBox.innerHTML = '';
        }
      },
      error: function(err, xhr, msg) {}
    })
  })

  $("#replyText").keyup(function(){
    var inputLength = $(this).val().length;
    $(".reply-actual").text(inputLength);
  })
</script>