Twitter-clone-2/app/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from tweets.views import Feed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Feed.as_view(), name='feed'),
    path('authentication/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls')),
    path('tweets/', include('tweets.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Twitter-clone-2/app/profiles/urls.py
from django.urls import path

from . import views 

app_name = 'profiles'

urlpatterns = [
    path('my/', views.MyProfile.as_view(), name='my'),
    path('edit/', views.ChangeProfile.as_view(), name='edit'),
    path('followed/', views.FollowedSection.as_view(), name='followed'),
    path('search/', views.ProfileSearch.as_view(), name='search'),
    path('interact/<int:user_id>/', views.interact, name='interact'),
    path('<slug:slug>/', views.ProfileDetail.as_view(), name='single'),
]

Twitter-clone-2/app/profiles/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse

User = settings.AUTH_USER_MODEL

from core import utils

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=64, unique=True)
    slug = models.SlugField(blank=True, unique=True, allow_unicode=True)
    nickname = models.CharField(blank=True, null=True, max_length=50)
    profile_pic = models.ImageField(upload_to='profiles/profile_pics', blank=True, null=True)
    bio = models.TextField(default='No bio provided yet.')
    reading = models.ManyToManyField(
        "self",
        related_name='reading_whom',
        blank=True,
        symmetrical=False
    )
    followers = models.ManyToManyField(
        "self",
        related_name='followers_who',
        blank=True,
        symmetrical=False
    )

    def __str__(self):
        return f"@{self.nickname}" if self.nickname else self.username

    def get_absolute_url(self):
        return reverse("profiles:single", kwargs={'slug': self.slug})
    
    @property 
    def reading_count(self):
        return self.reading_whom.all().count()
    
    @property 
    def followers_count(self):
        return self.followers_who.all().count()


@receiver(post_save, sender=User)
def post_signup_profile_creator(sender, instance, created, *args, **kwargs):
    if created:
        nick = ''
        if instance.full_name:
            nick = instance.full_name + utils.random_suffix(3)

        if instance.email:
            username = instance.email.split('@')[0] + utils.random_suffix(8)

        Profile.objects.get_or_create(
            user=instance,
            username=username,
            slug=slugify(username),
            nickname=nick or None
        )

Twitter-clone-2/app/profiles/forms.py
from django import forms 


class ProfileSettingsForm(forms.Form):
    
    nickname = forms.CharField(required=False, max_length=50)
    bio = forms.CharField(required=False, widget=forms.Textarea(attrs={
        'class': 'bio-input-box form-control',
        'maxlength': 140
    }))
    profile_pic = forms.ImageField(required=False)
    

Twitter-clone-2/app/profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.urls import reverse
from django.forms.models import model_to_dict
from django.http import JsonResponse

from tweets.forms import TweetForm

from .models import Profile
from .forms import ProfileSettingsForm

from tweets.models import Tweet

User = get_user_model()

# Create your views here.

class ProfileDetail(generic.DetailView):

    model = Profile
    lookup_field = 'slug'
    template_name = 'profiles/single.html'
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        tweet_ids = [i.id for i in context['profile'].tweets.all()]
        tweet_ids.extend([i.tweet.id for i in context['profile'].retweets.all()]) # getting retweets too 
        context['profile_tweets'] = Tweet.objects.filter(
            id__in=tweet_ids,
            is_reply=False
        ).time_order()
        context['retweets'] = [i.tweet for i in context['profile'].retweets.all()]
        liked_tweet_ids = [i.tweet.id for i in context['profile'].likes.all()]
        context['liked_tweets'] = Tweet.objects.filter(id__in=liked_tweet_ids)
        return context 


class MyProfile(LoginRequiredMixin, generic.View):

    def get(self, *args, **kwargs):
        request = self.request
        context = {
            'profile': request.user.profile,
            'tweet_form': TweetForm(),
            'tweet_form_action': reverse('tweets:new'),
            'profile_settings_form': ProfileSettingsForm(),
            'profile_settings_action': reverse('profiles:edit'),
            'retweets': [i.tweet for i in request.user.profile.retweets.all()]
        }
        # context['profile_tweets'] = context['profile'].tweets.filter(is_reply=False)
        tweet_ids = [i.id for i in request.user.profile.tweets.all()]
        tweet_ids.extend([i.tweet.id for i in request.user.profile.retweets.all()])
        context['profile_tweets'] = Tweet.objects.filter(
            id__in=tweet_ids,
            is_reply=False,
        )
        liked_tweet_ids = [i.tweet.id for i in context['profile'].likes.all()]
        context['liked_tweets'] = Tweet.objects.filter(id__in=liked_tweet_ids)
        return render(request, 'profiles/single.html', context)


class ChangeProfile(LoginRequiredMixin, generic.View):

    def post(self, *args, **kwargs):
        request = self.request
        profile_obj = request.user.profile
        form = ProfileSettingsForm(request.POST or None, request.FILES or None)

        if form.is_valid():
            form_data = form.cleaned_data
            truthy_values = {key:value for key, value in form_data.items() if form_data[key]}
            if request.FILES.get('profile_pic', None) is not None:
                img = request.FILES['profile_pic']
                truthy_values['profile_pic'] = img

            if truthy_values:
                profile_obj.__dict__.update(**truthy_values)
            profile_obj.save()
            return redirect('profiles:my')
        messages.warning(request, "WRONG PROFILE FORM!")
        return redirect('profiles:my')
    
    
@login_required 
def interact(request, user_id):
    current_profile_obj = request.user.profile
    target_user_profile = get_object_or_404(Profile, id=user_id)
    if target_user_profile in current_profile_obj.reading_whom.all():
        current_profile_obj.reading_whom.remove(target_user_profile)
        target_user_profile.followers_who.remove(current_profile_obj)
        followed = False
    else:
        current_profile_obj.reading_whom.add(target_user_profile)
        target_user_profile.followers_who.add(current_profile_obj)
        followed = True
    current_profile_obj.save(); target_user_profile.save()
    if request.is_ajax:
        data = {
            'followed': followed,
            'unfollowed': not followed,
            'followers_count': target_user_profile.followers_count,
        }
        return JsonResponse(data)
        
    return redirect('profiles:my')


class FollowedSection(LoginRequiredMixin, generic.View):
    
    def get(self, *args, **kwargs):
        request = self.request
        followed_profiles = [profile for profile in request.user.profile.reading.all()]
        tweets = []
        for profile in followed_profiles:
            tweets.extend([tweet for tweet in profile.tweets.all().filter(is_reply=False)])
        context = {
            'tweets': tweets,
            'hero_unit_msg': 'Check only those authors which interest you the most.',
            'hero_unit_class': 'info'
        }
        return render(request, 'feed.html', context)
    
    
class ProfileSearch(generic.View):
    
    def get(self, *args, **kwargs):
        request = self.request 
        
        query = request.GET.get('search-q')
        context = {
            'query': query
        }
        profile_qs = Profile.objects.filter(
            nickname__icontains=query
        ).union(Profile.objects.filter(
            username__icontains=query
        ))
        
        context['profiles'] = profile_qs or None 
        return render(request, "profiles/search-list.html", context)
    

Twitter-clone-2/app/profiles/templates/profiles/search-list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{query}}{% endblock title %}

{% block content %}
    
    <main class="my-3">
        <div class="p-5 bg-light text-dark fs-3 rounded">
            <h3>
                {% if profiles %}
                    Search results are displayed below.
                {% else %}
                    No profiles found for query {{query}}.
                {% endif %}
            </h3>
        </div>
        {% if profiles %}
        <div class="search-results-box">
            {% for profile in profiles %}
            <div class="d-flex position-relative p-3 border rounded">
                <img src="{% if profile.profile_pic %}{{profile.profile_pic.url}}{% else %}{% static 'images/no_photo_placeholder.png' %}{% endif %}" class="flex-shrink-0 me-3 profile-pic-medium" alt="...">
                <div>
                  <h5 class="mt-0">
                    <a href="{% if current_profile == profile %}{% url 'profiles:my' %}{% else %}{{profile.get_absolute_url}}{% endif %}">{{profile.nickname}}</a>
                  </h5>
                  <small class="text-muted">@{{profile.username}}</small>
                  <p class="fs-4">{{profile.bio}}</p>
                  <div class="d-flex gap-3">
                    <span class="badge bg-primary">{{profile.followers.count}} follower{{profile.followers.count|pluralize}}</span>
                    <span class="badge bg-primary">{{profile.reading.count}} reading</span>
                  </div>
                </div>
            </div>{% if forloop.counter != profiles.count %}<hr>{% endif %}
            {% endfor %}
        </div>
        {% endif %}
    </main>

{% endblock content %}

Twitter-clone-2/app/profiles/templates/profiles/single.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {% if request.user == profile.user %}
        My Profile
    {% else %}
        {{profile.username}} Profile
    {% endif %}
{% endblock title %}

{% block content %}
    <main class="py-3">
        <div class="p-5 bg-{% if request.user == profile.user %}success{% else %}primary{% endif %} mb-4 text-white">
            <div class="d-flex justify-content-between">
                <div class="d-flex flex-column nick-and-followers">
                    <h1 class="display-4">
                        {% if request.user == profile.user %}
                        My Profile
                        {% else %}
                        @{{profile.nickname}} Profile
                        {% endif %} <br>
                        <span class="h4">{{profile.nickname}}</span>
                    </h1>
                    <div class="d-flex flex-row followers gap-3">
                        {% include "profiles/snippets/dropdown.html" with dropdown_id="reading_id" dropdown_title="Reading" dropdown_user_types="READING" count=profile.reading_count %}
                        {% include "profiles/snippets/dropdown.html" with dropdown_id="followers_id" dropdown_title="Followers" dropdown_user_types="FOLLWOGIN" count=profile.followers_count %}
                    </div>
                </div>
                <p hidden="true" id="{{profile.slug}}-nick-now">{{profile.nickname}}</p>
                <p hidden="true" id="{{profile.slug}}-bio-now">{{profile.bio}}</p>
                <img src="{% if profile.profile_pic %}{{profile.profile_pic.url}}{% else %}{% static 'images/no_photo_placeholder.png' %}{% endif %}" alt="" class="profile-img shadow">
            </div>

            
            <p class="h3 mt-3">User's bio</p><hr>
            <p class="lead">{{profile.bio}}</p>
            {% if request.user == profile.user %}
            <div class="d-flex justify-content-between">
                <button class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#profileSettingsForm"><i class="fa fa-cog"></i> Profile settings</button>
                {% include "base/snippets/modal_form.html" with modal_id="profileSettingsForm" modal_label="profileSettingsLabel" label_text="Change something!" form_id="settingsFormId" form=profile_settings_form form_action=profile_settings_action %}
                <button class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#tweetModalForm"><i class="fa fa-pencil"></i> What's new?</button>
                {% include "base/snippets/modal_form.html" with modal_id="tweetModalForm" modal_label="tweetModalFormLabel" label_text="Tell something!" form_id="tweetFormId" form=tweet_form form_action=tweet_form_action %}
            </div>
            {% else %}
            <div class="d-flex flex-row-reverse">
                <button class="btn btn-outline-light interact-btn" data-index="{{profile.id}}">
                    {% if current_profile in profile.followers_who.all %}
                        Unfollow
                    {% else %}
                        Follow
                    {% endif %}
                </button>
            </div>
            {% endif %}
        </div>

        <ul class="nav nav-tabs d-flex justify-content-center fs-3" id="tweetsTab" role="tablist">
            <li class="nav-item" role="presentation">
              <button class="nav-link active" id="profile-tweets-tab" data-bs-toggle="tab" data-bs-target="#profile-tweets-tab-pane" type="button" role="tab" aria-controls="profile-tweets-tab-pane" aria-selected="true">
                {% if request.user == profile.user %}
                    My Tweets 
                {% else %}
                    {{profile.nickname}}'s Tweets
                {% endif %}
              </button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="profile-tweets-responses-tab" data-bs-toggle="tab" data-bs-target="#profile-tweets-responses-tab-pane" type="button" role="tab" aria-controls="profile-tweets-responses-tab-pane" aria-selected="false">
                    {% if request.user == profile.user %}
                        My Tweets and Responses 
                    {% else %}
                        {{profile.nickname}}'s Tweets and Responses
                    {% endif %}
                </button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link" id="profile-likes-tab" data-bs-toggle="tab" data-bs-target="#profile-likes-tab-pane" type="button" role="tab" aria-controls="profile-likes-tab-pane" aria-selected="false">
                {% if request.user == profile.user %}
                    My Likes 
                {% else %}
                    {{profile.nickname}}'s Likes
                {% endif %}
              </button>
            </li>
          </ul>
          <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="profile-tweets-tab-pane" role="tabpanel" aria-labelledby="profile-tweets-tab" tabindex="0">
            {% for tweet in profile_tweets.time_order %}
                {% include 'tweets/snippets/tweet.html' with tweet=tweet %}
            {% empty %}
                <h3 align="center" class="my-3">It's been silent here...</h3>
            {% endfor %}
            </div>
            <div class="tab-pane fade" id="profile-tweets-responses-tab-pane" role="tabpanel" aria-labelledby="profile-tweets-responses-tab" tabindex="0">
                {% for tweet in profile.tweets.all %}
                    {% include 'tweets/snippets/tweet.html' with tweet=tweet %}
                {% empty %}
                    <h3 align="center" class="my-3">So lonely, isn't it?...</h3>
                {% endfor %}
            </div>
            <div class="tab-pane fade" id="profile-likes-tab-pane" role="tabpanel" aria-labelledby="profile-likes-tab" tabindex="0">
            {% for tweet in liked_tweets %}
                {% include 'tweets/snippets/tweet.html' with tweet=tweet %}
            {% empty %}
                <h3 align="center" class="my-3">Nothing to show for now...</h3>
            {% endfor %}
            </div>

    </main>


<script type="text/javascript">
    $(document).ready(function(){

        // profile settings form autofill
        var settingsForm = $('#profileSettingsForm')
        var currentNick = document.getElementById("{{profile.slug}}-nick-now");
        var currentBio = $("#{{profile.slug}}-bio-now");

        settingsForm.find('#id_nickname').attr('value', currentNick.innerHTML);
        settingsForm.find('#id_bio').val(currentBio.text())

        // char count section 
        $("#tweet-text-box").keyup(function(){
            var inputLength = $(this).val().length;
            $(".actual").text(inputLength);
        })

        $(".bio-input-box").keyup(function(){
            var inputLength = $(this).val().length;
            $(".actual").text(inputLength)
        })

        // async follow-unfollow
        $('.interact-btn').click(function(){
            var targetId = $(this).data('index');
            $.ajax({
                url: "{% url 'profiles:interact' user_id=profile.id %}",
                type: "POST",
                data: {
                    'user_id': targetId,
                    'csrfmiddlewaretoken': '{{csrf_token}}'
                },
                success: function(json){
                    $('.followers-count').text(json.followers_count);
                    if (json.followed){
                        $('.interact-btn').text('Unfollow')
                    }else if(json.unfollowed) {
                        $('.interact-btn').text('Follow')
                    }
                },
                error: function(xhr) {}
            })
        })
            })
  
</script>
{% endblock content %}